### PR TITLE
peer_discovery: add a workaround for Android hotspot

### PR DESCRIPTION
**Pull request by Lanius-collaris**

### CODE REVIEW

**Review by aberaud — APPROVED** [review]
Thanks

**Comment by Lanius-collaris** [comment]
Sorry. I forgot to modify reDiscover().

**Comment by AmnaSnene** [comment]
@Lanius-collaris  Could you clarify why you only take into account IPv4 interfaces?

**Comment by Lanius-collaris** [comment]
@AmnaSnene On android, we always have a route to dummy0 (e.g. `multicast ff00::/8 dev dummy0 table local proto kernel metric 256 pref medium`), so it's impossible to encounter "No such device" error when setting `asio::ip::multicast::join_group` option for IPv6.
You can try `adb shell ip route get ff08::101` when WLAN, mobile data and hotspot are OFF.

**Pull request merged**
