### PR TITLE
C: build bindings and tools with autotools

### PR DESCRIPTION
**Pull request by aberaud**

### CODE REVIEW

**Comment by aberaud** [comment]
@ghenry ^

**Review by ghenry — COMMENTED** [review]
Looks good, but I also get:

```
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  g++ -std=c++17 -DHAVE_CONFIG_H -I. -I.. -isystem ../include -DOPENDHT_JSONCPP -O3 -pedantic-errors -DMSGPACK_NO_BOOST -DMSGPACK_DISABLE_LEGACY_NIL -DMSGPACK_DISABLE_LEGACY_CONVERT -MT opendht.lo -MD -MP -MF .deps/opendht.Tpo -c opendht.cpp  -fPIC -DPIC -o .libs/opendht.o
In file included from ../include/opendht/dhtrunner.h:25,
                 from ../include/opendht.h:21,
                 from opendht.cpp:20:
../include/opendht/value.h:42:10: fatal error: json/json.h: No such file or directory
   42 | #include <json/json.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:485: opendht.lo] Error 1
```

**Comment by ghenry** [comment]
> Looks good, but I also get:
> 
> ```
> mv -f $depbase.Tpo $depbase.Plo
> libtool: compile:  g++ -std=c++17 -DHAVE_CONFIG_H -I. -I.. -isystem ../include -DOPENDHT_JSONCPP -O3 -pedantic-errors -DMSGPACK_NO_BOOST -DMSGPACK_DISABLE_LEGACY_NIL -DMSGPACK_DISABLE_LEGACY_CONVERT -MT opendht.lo -MD -MP -MF .deps/opendht.Tpo -c opendht.cpp  -fPIC -DPIC -o .libs/opendht.o
> In file included from ../include/opendht/dhtrunner.h:25,
>                  from ../include/opendht.h:21,
>                  from opendht.cpp:20:
> ../include/opendht/value.h:42:10: fatal error: json/json.h: No such file or directory
>    42 | #include <json/json.h>
>       |          ^~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [Makefile:485: opendht.lo] Error 1
> ```

Ah, this was my issue. I thought I had this installed. Can we version this too so I can rebuild the Deb files?

**Comment by aberaud** [comment]
> > Looks good, but I also get:
> > ```
> > mv -f $depbase.Tpo $depbase.Plo
> > libtool: compile:  g++ -std=c++17 -DHAVE_CONFIG_H -I. -I.. -isystem ../include -DOPENDHT_JSONCPP -O3 -pedantic-errors -DMSGPACK_NO_BOOST -DMSGPACK_DISABLE_LEGACY_NIL -DMSGPACK_DISABLE_LEGACY_CONVERT -MT opendht.lo -MD -MP -MF .deps/opendht.Tpo -c opendht.cpp  -fPIC -DPIC -o .libs/opendht.o
> > In file included from ../include/opendht/dhtrunner.h:25,
> >                  from ../include/opendht.h:21,
> >                  from opendht.cpp:20:
> > ../include/opendht/value.h:42:10: fatal error: json/json.h: No such file or directory
> >    42 | #include <json/json.h>
> >       |          ^~~~~~~~~~~~~
> > compilation terminated.
> > make[2]: *** [Makefile:485: opendht.lo] Error 1
> > ```
> 
> Ah, this was my issue. I thought I had this installed. Can we version this too so I can rebuild the Deb files?

fixed !

**Pull request merged**
